{{ if .Values.database }}
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: postgres
spec:
  hosts:
    - {{ .Values.database.host }}
  ports:
    - number: {{ .Values.database.port }}
      name: tcp-postgres
      protocol: TCP
  resolution: NONE
  location: MESH_EXTERNAL
{{ end }}