apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "name" . }}
spec:
  hosts:
    - {{ .Values.service.name }}
    - "{{ .Values.service.name }}.ibmgarageforcloud.com"
  gateways:
    - "react-items-ui"
  http:
    - route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: 8080
          weight: 100
      timeout: 10s
