server:
  shutdown: graceful
api:
  path: /api/v1/items
management:
  server:
    port: 9001
  endpoint:
    health:
      enabled: true
      show-details: "ALWAYS"
  endpoints:
    web: 
      exposure:
        include: "health"
spring:
  profiles: default
  application:
    name: loanrequests-api
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: false
        max-page-size: 2000
  datasource:
    url: jdbc:mysql://localhost:3306/archetype
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${mysql_username}
    password: ${mysql_password} # dummy password,
  #data:
  #  mongodb:
  #    authentication-database: admin
  #    database: bofa_patterns_dev
  #    port: 27017
  #    host: localhost
  #datasource:
  #  username: sa
  #  password: 
  #  driverClassName: org.h2.Driver
  #  url: jdbc:h2:mem:testdb
  #  initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    #database-platform: org.hibernate.dialect.H2Dialect
  redis:  
    host: localhost
    port: 6379

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.ibm.github.michaelhepfer.items: TRACE