replicaCount: 2
revisionHistoryLimit: 3
subset:
  version: v1
image:
  repository: michaelsteven
  name: springboot-items-api
  tag: 0.0.1
  pullSecret: pull-secret
  pullPolicy: Always
  runAsUser: 1001
service:
  name: springboot-items-api
  type: ClusterIP
  servicePort: 80
  appPort: 8080
  livenessPort: 9001
gateway:
  name: ibmgarageforcloud-com.istio-system
  appName: springboot-items-api
  host: springboot-items-api.ibmgarageforcloud.com
certificate:
  tlsSecret:
    name: ibmgarageforcloud-com-tls
